substitutions:
  device_name: halcyon-ou
  friendly_name: Fujitsu Halcyon
  device_description: Atom Lite + FOSV
  esp_board: m5stack-atom

external_components:
  - source: github://Omniflux/esphome-tzsp
  - source: github://Omniflux/esphome-fujitsu-dmmum

packages:
  wifi: !include common/wifi.yaml

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: ${device_description}

esp32:
  board: ${esp_board}
  framework:
    type: esp-idf

api:

logger:
  level: DEBUG

button:
  - platform: restart
    name: Restart
  - platform: safe_mode
    name: Restart (Safe Mode)

ota:
  - platform: esphome
    password: !secret ota_password

uart:
  tx_pin: GPIO22  # Device dependent
  rx_pin: GPIO19  # Device dependent
  baud_rate: 500
  parity: EVEN

sensor:
  - platform: uptime
    name: Uptime

  # Use Home Assistant sensors for current temperature and humidity
  # These are for display only; Fujitsu units will not use these
  - platform: homeassistant
    id: room_1_sensor_temperature # ESPHome sensor name
    entity_id: sensor.room_1_sensor_temperature # Home Assistant sensor name
    unit_of_measurement: "°F" # Cannot be auto-detected, must specify if not °C
  - platform: homeassistant
    id: room_2_sensor_temperature
    entity_id: sensor.room_2_sensor_temperature
    unit_of_measurement: "°F"
  - platform: homeassistant
    id: room_3_sensor_temperature
    entity_id: sensor.room_3_sensor_temperature
    unit_of_measurement: "°F"
  - platform: homeassistant
    id: room_4_sensor_temperature
    entity_id: sensor.room_4_sensor_temperature
    unit_of_measurement: "°F"
  - platform: homeassistant
    id: room_5_sensor_temperature
    entity_id: sensor.room_5_sensor_temperature
    unit_of_measurement: "°F"

  - platform: homeassistant
    id: room_1_sensor_humidity
    entity_id: sensor.room_1_sensor_humidity
  - platform: homeassistant
    id: room_2_sensor_humidity
    entity_id: sensor.room_2_sensor_humidity
  - platform: homeassistant
    id: room_3_sensor_humidity
    entity_id: sensor.room_3_sensor_humidity
  - platform: homeassistant
    id: room_4_sensor_humidity
    entity_id: sensor.room_4_sensor_humidity
  - platform: homeassistant
    id: room_5_sensor_humidity
    entity_id: sensor.room_5_sensor_humidity

fujitsu_general_airstage_h_central_controller:
#  tzsp:
#    ip: 192.168.12.23
#    protocol: 254

climate:
  - platform: fujitsu_general_airstage_h_central_controller
    indoor_unit: 1
    name: Room 1
    sensor: room_1_sensor_temperature # Optional
    humidity_sensor: room_1_sensor_humidity # Optional
  - platform: fujitsu_general_airstage_h_central_controller
    indoor_unit: 2
    name: Room 2
    sensor: room_2_sensor_temperature
    humidity_sensor: room_2_sensor_humidity
  - platform: fujitsu_general_airstage_h_central_controller
    indoor_unit: 3
    name: Room 3
    sensor: room_3_sensor_temperature
    humidity_sensor: room_3_sensor_humidity
  - platform: fujitsu_general_airstage_h_central_controller
    indoor_unit: 4
    name: Room 4
    sensor: room_4_sensor_temperature
    humidity_sensor: room_4_sensor_humidity
  - platform: fujitsu_general_airstage_h_central_controller
    indoor_unit: 5
    name: Room 5
    sensor: room_5_sensor_temperature
    humidity_sensor: room_5_sensor_humidity