esphome:
  devices:
    - id: ${id}_climate
      name: ${name}

climate:
  - platform: fujitsu_general_airstage_h_central_controller
    indoor_unit: ${unit_number}
    name: None
    id: ${id}
    device_id: ${id}_climate

binary_sensor:
  - platform: fujitsu_general_airstage_h_central_controller
    indoor_unit_id: ${id}
    incompatible_mode:
      name: Incompatible Mode
      device_id: ${id}_climate
    error_state:
      name: Error
      device_id: ${id}_climate

switch:
  - platform: fujitsu_general_airstage_h_central_controller
    indoor_unit_id: ${id}
    min_heat:
      name: Minimum Heat Mode
      device_id: ${id}_climate
    rc_prohibit:
      name: RC Prohibit
      device_id: ${id}_climate
